# Generated by Django 4.1.5 on 2023-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
