# Generated by Django 4.1.5 on 2023-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard_project', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
