# Generated by Django 4.1.5 on 2023-01-22 17:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('callboard_project', '0002_reply_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
