# Generated by Django 4.1.5 on 2023-01-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard_project', '0003_post_image_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
