# Generated by Django 4.1.5 on 2023-01-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard_project', '0004_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(through='callboard_project.Subscribers', to='callboard_project.verifieduser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard_project.verifieduser'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard_project.verifieduser'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard_project.verifieduser'),
        ),
    ]
